Acceptance tests functions added to cover new RB admin REST endpoints
Activiti/activiti-cloud-acceptance-tests pull request #109
Opened 2019-01-29 15:10 UTC by CTI777

Related to https://github.com/Activiti/Activiti/issues/2420

2019-01-31 09:27 UTC, erdemedeiros requested changes
Some small details.

2019-01-31 09:27 UTC, erdemedeiros commented on activiti-cloud-acceptance-tests-core/src/main/java/org/activiti/cloud/acc/core/services/runtime/admin/ProcessRuntimeAdminService.java
> +    @Headers("Content-Type: application/json")
I don't think this header is necessary as you are not providing any body content to the request, only the `id` directly in the URL path.

2019-01-31 09:27 UTC, erdemedeiros commented on activiti-cloud-acceptance-tests-core/src/main/java/org/activiti/cloud/acc/core/services/runtime/admin/TaskRuntimeAdminService.java
> +            "Content-Type: application/json",
I don't think `Content-type` is necessary here, `Accept` should be enough.

2019-01-31 11:13 UTC, CTI777 commented on activiti-cloud-acceptance-tests-core/src/main/java/org/activiti/cloud/acc/core/services/runtime/admin/TaskRuntimeAdminService.java
> +            "Content-Type: application/json",
Then it seems that I have to change headers for other RequesLlines. I will do refactoring for RB only...

2019-02-01 08:18 UTC, erdemedeiros approved these changes

2019-02-01 08:18 UTC, merged